### ISSUE TITLE
Order Parts

### ISSUE THREAD

**Issue by spartanhaden** [MTU-Autobot/charlie-code#1]
Order parts for the Interface board

**Comment by qwertyboy** [comment]
Why is this in the code repo

**Comment by qwertyboy** [comment]
Mouser order placed, still need a MKL02 chip (QFN-16): http://www.pjrc.com/store/ic_mkl02.html

**Comment by qwertyboy** [comment]
PJRC order placed, issue can be closed. @spartanhaden
